menu = ix.application.get_main_menu()

menu.add_command("Animate>")
menu.add_show_callback("Animate>", "./_show.py")

menu.add_command("Animate>Previous Frame", "./previous_frame.py", ",")
menu.add_command("Animate>Next Frame", "./next_frame.py", ".")
menu.add_command("Animate>separator")
menu.add_command("Animate>Previous Keyframe", "./previous_keyframe.py", "shift+,")
menu.add_command("Animate>Next Keyframe", "./next_keyframe.py", "shift+.")
menu.add_command("Animate>separator")
menu.add_command("Animate>Set Motion Key...", "./set_motion_key.py", "enter")
menu.add_command("Animate>Delete Motion Key...", "./delete_motion_key.py")
menu.add_command("Animate>separator")
menu.add_command("Animate>Center Pivot To BBox", "./center_pivots_to_bbox.py")
menu.add_command("Animate>Center Pivot To Ground", "./center_pivots_to_ground.py")
menu.add_command("Animate>Reset Pivots", "./reset_pivots.py")
menu.add_command("Animate>Conform Pivots", "./conform_pivots.py", "", "Move transform pivots to item's global pivot.")
menu.add_command("Animate>Remove Offsets", "./remove_offsets.py")
menu.add_command("Animate>Record Offsets", "./record_offsets.py")
menu.add_command("Animate>separator")
menu.add_command("Animate>Reset Transforms", "./reset_transforms.py")
