# @a Add this to ~/.bashrc and adjust path
# @cr Linux
export PYTHONPATH="${PYTHONPATH}:/opt/clarisse/python/"
# @cr Windows
export PYTHONPATH="${PYTHONPATH}:/c/Program\ Files/Isotropix/Clarisse\ iFX\ 4.0\ SP3/Clarisse/python/"

